### PR TITLE
Improve interface

### PR DESCRIPTION
**Pull request by ritiek**
I've made several changes to the API:

- Rename `kick` method to `kickByClientID`.
- Implement `kickByPlayerID`.
- Add methods: `setPunchPowerScale`, `setPunchCoolDown`, `setImpactScale`, `setBombCount` and `setBlastRadius`.
- Get additional player data (including `team`, `account`, etc.) in `getPlayers()`.
- Add an optional parameter `switch` to `speedup`, `fly`, `invincible`, `freeze` which can either be `True` or `False` to enable or disable player powerups respectively.
- Create method `_make_command` to avoid code repetition.
- Add docstrings to methods in `manager.py` and relevant examples to README.

There is still need to implement `spawnPlayer` and `spawnBomb` methods (as you suggested in README) but I think we should open a separate issue for it.

### CODE REVIEW

**Comment by ch0c0l8ra1n** [comment]
Hey ritiek, thanks a bunch.

**Comment by ritiek** [comment]
Thanks for starting this project. By the way, I think we should also add a LICENSE to the repository. MIT License usually works good for hobby open-source projects but of course you're free to add the one you like!

**Comment by ch0c0l8ra1n** [comment]
I just did! Now that it's getting some traction, I think I'll make a few more changes. What server do you play on?

**Comment by ritiek** [comment]
Lol, I am trying to lower down my addiction and spend more time coding but I usually play teams without mods, mainly "MELLOW SERVER".

**Pull request merged**
